### ISSUE TITLE
 high-risk vulnerability (NVDB-CNVDB-2023674205)

### ISSUE THREAD

**Issue by parchk** [alibaba/nacos#10060]
Notified by the Net Security Bureau of the Ministry of Industry and Information Technology, recently, the Ministry of Industry and Information Technology Network Security Threat and Vulnerability Information Sharing Platform detected that the open source service management platform Nacos has an authentication bypass high-risk vulnerability (NVDB-CNVDB-2023674205), details of which are as follows.
     Nacos is a service management platform for building cloud-native applications, and its key is not modified under the default configuration, resulting in an attacker being able to bypass key authentication to enter the backend, leading to consequences such as a controlled system. The vulnerability hazard level is high risk, affecting versions 0.1.0~2.2.0.

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/blog/announcement-token-secret-key.html
https://nacos.io/zh-cn/blog/announcement-token-secret-key.html

Please check your env `token.secret.key`, if use default value and export to public network, **most** change the `token.secret.key` as soon as possible.

if only use default value and not export to public network, please change the `token.secret.key` quickly.

If no use default value or use custom auth plugins , the risk is not effect your env. But we suggest you **not** export to public networks.

**Comment by starsoulatnight** [comment]
what if our environment setting is nacos.core.auth.enabled=false. It that dangerous?

**Comment by hi-unc1e** [comment]
Additional Information:
- After analyzing, this issues  is essentially [CVE-2021-43116](https://www.cve.org/CVERecord?id=CVE-2021-43116)，see  #7127，#7182
![image](https://user-images.githubusercontent.com/67778054/225187458-6e5f9764-267c-4a90-bc63-1756d278b02c.png)

- Actually due to a hardcoded JWT secret,  if not changed, will cause auth-bypass
- Now it's fixed, see: [https://avd.aliyun.com/detail?id=AVD-2023-1655789](https://avd.aliyun.com/detail?id=AVD-2023-1655789)
