### ISSUE TITLE
Is there a solution to migrate Nacos Derby to MySQL?

### ISSUE THREAD

**Issue by weifeng32** [alibaba/nacos#10615]
- Current situation:

Nacos version 2.0.3 is deployed in cluster mode with embedded storage, which theoretically should provide high availability. However, during actual operations, when one of the nodes is shut down, the logs show the following error: `com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 500, errMsg: java.util.concurrent.ExecutionException: com.alibaba.nacos.consistency.exception.ConsistencyException: The conformance protocol is temporarily unavailable for reading, No leader at term 8442. `
All requests result in errors.

- Questions:

1. Will using embedded storage in a Nacos cluster lead to a loss of cluster high availability?
2. If using MySQL can solve this problem, is it possible to migrate Derby to MySQL?

**Comment by KomachiSion** [comment]
1. derby is not a cluster mode database, only a single node database with each node, so nacos cluster mode with embedded storage use jraft to change the derby database as a cluster database. It's need you understand how to maintain the raft status. From your error info, your cluster has no leader in derby cluster. So you should know how to solve the no leader status before you make sure you use cluster mode with embedded storage, otherwise no one can help you ensure the high availability.

2. MySQL is extranel one node or cluster database, which is deploy out of nacos cluster, so nacos don't need the jraft to make it(them) data consistency, so no `no leader` error for this case. But for high availability, you also should know how to maintain the relationships bewteen nacos and database, otherwise on one can help you ensure the high availability.
