### ISSUE TITLE
Version 2.2.3 entered the nacos home page, the report “user not found” error

### ISSUE THREAD

**Issue by javajianghu** [alibaba/nacos#10872]
# 问题：2.2.3版本进入nacos首页，报user not found错误

操作步骤

1、我下载了最新的源码，切换到develop分支，修改application.properties后，并启动Nacos.java
2、然后到浏览器输入：[http://127.0.0.1:8848/nacos](http://127.0.0.1:8848/nacos)，回车，然后页面提示：user not found,并且弹框：权限认证失败：没有 命名空间的访问权限！
3、打开浏览器控制台，发现是这个请求返回的403，use not found报错。

> http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=blur

我的疑问：
- 还没有登录，为什么要调用/v1/cs/configs

For English
# Problem: Version 2.2.3 entered the nacos home page, the report user not found error
operating steps
1、I downloaded the latest source code, switched to the develop branch, modified application.properties, and started Nacos.java
2、 and then to the browser input: [http://127.0.0.1:8848/nacos] (http://127.0.0.1:8848/nacos), enter, then page tip: user not found, and bounced: access authentication failed: no namespace access!
3、Open the browser console, find that this request returned 403, use not found error.
> http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=blur

 My question:
- Why call /v1/cs/configs when you are not logged in

**Comment by KomachiSion** [comment]
2.2.2版本之后，在不开启鉴权的情况下不再有登陆框， 默认首页是nacos的配置中心页面， 配置中心页面需要查询当前命名空间的配置列表，就是你上面这个接口。

建议你看下鉴权的文档，确认下是否开启了鉴权，同时又没有设置正确的相关配置信息。

**Comment by javajianghu** [comment]
> 2.2.2版本之后，在不开启鉴权的情况下不再有登陆框， 默认首页是nacos的配置中心页面， 配置中心页面需要查询当前命名空间的配置列表，就是你上面这个接口。
> 
> 建议你看下鉴权的文档，确认下是否开启了鉴权，同时又没有设置正确的相关配置信息。

修改了application.properties，我想要登录后才进入到配置中心页面，所以开启了鉴权，按照https://nacos.io/zh-cn/docs/auth.html进行了如下修改。
>
nacos.core.auth.enabled=true 
nacos.core.auth.server.identity.key=mykey 
nacos.core.auth.server.identity.value=mykey 
nacos.core.auth.plugin.nacos.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789

**Comment by KomachiSion** [comment]
清理浏览器缓存后重试

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by stevensilvas655** [comment]
各位老兄:
Nacos2.2.3版本這問題後來是如何解決的? 能不能再給點提示或指引?

**Comment by javajianghu** [comment]
> 各位老兄: Nacos2.2.3版本這問題後來是如何解決的? 能不能再給點提示或指引?

访问：http://127.0.0.1:8848/nacos   就会有这个问题
访问：http:127.0.0.1:8848/nacos/#/login?namespace=&pageSize=&pageNo=   就没有这个问题

最后我也没有管这个事情，反正就是登录界面有个弹框而已，关闭后，输入用户名密码就可以了。

**Comment by lt5227** [comment]
强迫症看到这个信息很不爽啊😂

**Comment by 1113126226** [comment]
我2.4版本最新的了，根据官网开启鉴权，初始化密码后不让登录了，怎么解决啊

**Comment by miclosgyjf** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.
