### ISSUE TITLE
when i after the invasion, i think about the problem

### ISSUE THREAD

**Issue by ASelince** [alibaba/nacos#10968]
Hello, we found a scene while using Nacos
After I log in, if I get a configs request using the interceptor, direct access to the interface elsewhere will get all of my configuration information.

Actual scenario:
During log monitoring after the network intrusion, I can obtain the access_token and other information carried by the access, and then I can obtain the account password of the configuration information under the configuration center

propose:
Whether the configured SecretKey and SecretValue can be dynamically added to the request Header?

**Comment by KomachiSion** [comment]
1. make sure you open the auth feature first.
2. After open auth feature, request must contain access_token or username password, otherwise 403.
3. If the default auth plugin can't accept your request, you can develop your own auth plugin to do any auth feature, doc: https://nacos.io/zh-cn/docs/v2/plugin/auth-plugin.html
