### ISSUE TITLE
nacos2.2.1 registers permanent instances, health status displays unhealthy.

### ISSUE THREAD

**Issue by mxoop** [alibaba/nacos#11233]
When the service is a temporary instance, the health status is normal. After changing to a permanent instance, the health status is displayed as false, but the service starts normally without errors.

**Comment by KomachiSion** [comment]
persistent service will do health check by tcp or http, please make sure your configuration of health check is right ( include ip ,port, uri and so on).

ephemeral service use heart beat to do health check, so no need any config, only make sure the client still work and network ok so that beat request can reach nacos server.

**Comment by mxoop** [comment]
我知道这个健康检查机制。nacos部署在虚拟机，而服务又是在本地启动的，导致nacos server下探失败

**Comment by KomachiSion** [comment]
那就是网络不通导致的， 不健康是正常的
