### ISSUE TITLE
nacos-server端的权限管理

### ISSUE THREAD

**Issue by lixianli1987** [alibaba/nacos#11412]
nacos-server端开启鉴权，且分配账号test/test，该账号设置只读权限。
此时nacos-client获取配置信息正常，但是注册到nacos-server端时，报错403，当test账号权限改成rw时，注册可以成功。
请问：nacos-client注册naocs-server端时，为啥需要写权限呢？

**Comment by Daydreamer-ia** [comment]
注册实例会变更服务目录，变更操作需要写权限这个应该没问题吧

**Comment by YuShiwen** [comment]
1.Whether it is on the Nacos-client or the Nacosfront-end page, read and write permissions are separated, with r permission being able to read and w permission being able to write.

2.The test account only has r permission and no w permission, so it can only read and cannot write.The core process of writing in the nacos client is the same as writing in the nacos front-end page.

3.The reason for separating read and write permissions is to prevent some users from randomly modifying data on the server.

4.Imagine in a formal environment where some developers need read permission to view specific configuration values in order to troubleshoot issues, but you cannot open write permission to them, otherwise they will randomly modify the production configuration, and the consequences will be unimaginable.

1.不管是在nacos-client还是在nacos前端页面，读写权限是分开，r权限可以读取，w权限可以写入；
2.test账号只有r权限，没有w权限，所以只能读取不能写入；在nacos-client写入和在nacos前端页面写入核心流程是一样的。
3.之所以把读写权限分开，就是为了不让一些用户随意修改服务端的数据。
4.设想一下在正式环境中，有一些开发为了排查问题，需要读权限查看具体配置的值，但是你不可以把写权限开放给他，要不然他乱改生产的配置，后果不堪设想。

**Comment by Daydreamer-ia** [comment]
> In my humble opinion：
> 
> 1.Whether it is on the Nacos-client or the Nacosfront-end page, read and write permissions are separated, with r permission being able to read and w permission being able to write.
> 
> 2.The test account only has r permission and no w permission, so it can only read and cannot write.The core process of writing in the nacos client is the same as writing in the nacos front-end page.
> 
> 3.The reason for separating read and write permissions is to prevent some users from randomly modifying data on the server.
> 
> 4.Imagine in a formal environment where some developers need read permission to view specific configuration values in order to troubleshoot issues, but you cannot open write permission to them, otherwise they will randomly modify the production configuration, and the consequences will be unimaginable.
> 
> 个人愚见： 1.不管是在nacos-client还是在nacos前端页面，读写权限是分开，r权限可以读取，w权限可以写入； 2.test账号只有r权限，没有w权限，所以只能读取不能写入；在nacos-client写入和在nacos前端页面写入核心流程是一样的。 3.之所以把读写权限分开，就是为了不让一些用户随意修改服务端的数据。 4.设想一下在正式环境中，有一些开发为了排查问题，需要读权限查看具体配置的值，但是你不可以把写权限开放给他，要不然他乱改生产的配置，后果不堪设想。

现在的模式就是读写分离的，你的意思是说client账号和frontend账号不要互通？如果有特殊需求的话，可以看一下自己实现[鉴权插件](http://nacos.io/zh-cn/docs/v2/plugin/auth-plugin.html)

**Comment by lixianli1987** [comment]
> No more response from author, It seems usage problem.

嗯嗯 采用如上兄弟的方案是可以解决的
