### ISSUE TITLE
本地开发阶段优先使用本地IP服务 方案 咨询 how can I prefer local IP when local development stage

### ISSUE THREAD

**Issue by lehug** [alibaba/nacos#11851]
I search the internet, there are some solution that must code to let the load balance to prefer local IP， I think a configuration is better.But I don't get the configuration solution from the internet and the issue.

So I ask here, wait for a good solution to reach the goal that local develop stage can automatically prefer local IP service, thanks

**Comment by KomachiSion** [comment]
It's not nacos' problem, If you want to register service instance with local ip, you should get local ip and call the register api to replace the default ip.

**Comment by lehug** [comment]
yes, it's not about problem. It's a solution with local develop case. I want to know if there is an easy way to reach that goal? Thanks @KomachiSion

**Comment by lehug** [comment]
The question is not about registering a server instance with a local IP. It is about how, when retrieving a service instance, we can ensure that the same IP instance is returned instead of following other load balancing algorithms. Is there a configuration method that can achieve this goal?

**Comment by KomachiSion** [comment]
I don't know the key usage in your application, for nacos, nacos support you register service with any ip and port without any configuration. And nacos only help to discovery the service instance list, you can subscribe the services with your own listener and do the select logic in custom listener.

So we are confused your problem, we don't know what's your said configuration to achieve this goal.

If you use some framework to run you app, you should move this issue to framework community, Such as Spring cloud, dubbo and more.

**Comment by lehug** [comment]
the scenario is at development stage. as a group of micro service, some of them is common, and I don't change it, so I want to use the common one. But some service I change it, and in development stage, nacos service has both common version and the new version in my local PC. I want to debug it use my local PC version. 

I search the internet, as you say, I can code and custom the listener, but I think it is a litter complex. I think by config is better than hard code. So I ask for the solution. 

I think this is a common case. Hope you understand my scenario. Thanks

**Comment by lehug** [comment]
the scenario is at development stage. as a group of micro service, some of them is common, and I don't change it, so I want to use the common one. But some service I change it, and in development stage, nacos service has both common version and the new version in my local PC. I want to debug it use my local PC version. 

I search the internet, as you say, I can code and custom the listener, but I think it is a litter complex. I think by config is better than hard code. So I ask for the solution. 

I think this is a common case. Hope you understand my scenario. Thanks

**Comment by KomachiSion** [comment]
It's your custom case I think. 

For most users, when development requires calling downstream common base services in the development environment, it is standard practice to directly use these base services. However, if one wishes to mock these common services, it's common to create a separate, isolated namespace or deploy a private Nacos environment for development purposes. In your case, you want to have both locally mocked development instances and other common environment instances under a single service. Furthermore, you wish to implement custom routing logic within the same service to prioritize the selection of locally mocked downstream services. Therefore, this routing logic is a unique requirement specific to your scenario, which extends beyond the general logic scope of Nacos. It involves moving into the data plane aspect of business traffic flow, rather than just discovering a list of service instances.

So one way is you implement your route logic by your rpc structure extension or you directly implement in nacos listener.
Or suggest you use standard usage.

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
