### ISSUE TITLE
The Nacos 2. x version occasionally experiences inconsistent configuration updates in cluster mode

### ISSUE THREAD

**Issue by CCTV-six** [alibaba/nacos#11953]
**Describe the bug**
In Nacos cluster mode, when a client attempts to update the configuration, other clients or the Nacos console may not always be able to immediately see the latest configuration content. This may lead to inconsistent behavior between services, as not all service instances are loaded with the same configuration.

**Expected behavior**
In Nacos cluster mode, when a client updates its configuration, other clients and the Nacos console should be able to immediately see the latest configuration content to ensure consistency of the configuration.

**Comment by KomachiSion** [comment]
Can you describe your operation and deploy way?

For design, Nacos console is query database directly, if you update configuration successfully, console will get the latest content.

And For nacos client, if you use listen way to get the config change, we can ensure the listen callback is latest content by md5.

There are some wrong usages or deploy way cause you get old content:
1. deploy with mutilple database which is dependent.
2. use getConfig api rather than use listen api to get config change and don't check content md5 .
3. directly modified content in database, which will casue nacos server can't know the content modified.

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem or env deploy problem.
