### ISSUE TITLE
 Let Nacos SDK support client-side load balancing strategies selector and customization

### ISSUE THREAD

**Issue by pguo65535** [alibaba/nacos#122]
[Descrption]

Now Nacos support only round robin service instance load balance  strategy，we should support more flexible  strategy by allow consumer specify&inject customization load balancing strategy 

**Describe the solution you'd like**

we may add following API in our SDK:

getInstance(String serverviceNamce, List<Selector> instanceSelectors) ();

**Describe alternatives you've considered**
the load balance should consider as per Service level or per Consumer level??

**Additional context**
In Spring Cloud and Dubbo context, Nacos do not have to do so as Spring Cloud has Ribbon and Dubbo Client has embedded load balance policies

**Comment by XCXCXCXCX** [comment]
@i will solve it@

**Comment by XCXCXCXCX** [comment]
@pguo65535 
I have some doubts. How to use a list of load balancing strategies to choose an instance from instances?

**Comment by nkorange** [comment]
@XCXCXCXCX Can you briefly introduce the design ideas of your commits? Client side load-balance is a very important feature, like Ribbon of Netflix, we should have more discussion before we commit the real code.

**Comment by XCXCXCXCX** [comment]
@nkorange 
Ok, first of all, dubbo or the ribbon already provides client load balancing. Nacos only needs to provide load balancing services for other native components. I added four call interfaces to the client-api, namely:

Instance selectOneHealthyInstance(String serviceName,LoadBalancerEnum balancerEnum) throws a NacosException;

Instance selectOneHealthyInstance(String serviceName, List <String> clusters, LoadBalancerEnum balancerEnum) throws a NacosException;

The instance selectOneHealthyInstance(String serviceName,LoadBalancer loadBalancer) throws a NacosException;

The instance selectOneHealthyInstance(String serviceName, List <String> clusters, LoadBalancer loadBalancer) throws a NacosException;

They provide a load balancing algorithm implemented by nacos or a user-implemented load balancing algorithm. The user needs to implement the LoadBalancer interface, obtain a list of instances according to ServiceInfo, and select an instance according to the policy.

However, in order to poll such a policy, it is necessary to determine if the list of instances has changed to adjust the polling state, so I use EventListener to listen for changes in the list of instances, and since the listener event might listen for the same list, I The Chooser Equals method was rewritten to determine if a polling list needs to be replaced.

In addition, the weighted polling strategy is implemented based on Nginx weighted polling, which allows a more even access to the weighted polling instance list.

**Comment by XCXCXCXCX** [comment]
@nkorange
I think we should discuss whether load balancing should be implemented using a listener or using a synchronous http request to get a list, or provide users with two ways to customize the interface. In my opinion, the way the listener might It will be relatively better. When the list of instances is too large, the way of the listener will behave better, although the real-time performance is not strong and the time-consuming equals is done in the filtering process (you may use the more optimized equals operation here) , but can provide a stable service; but if you use synchronous http request, it may cause a large load on the server, each request will delay processing, which may be unacceptable to users.

**Comment by XCXCXCXCX** [comment]
@nkorange 
I modified some code and can now provide it to the user.
1. Using the implementation of the listener 2. Synchronizing the implementation of the http request
By providing the enableListener parameter boolean value

**Comment by nkorange** [comment]
@XCXCXCXCX Please pause your commit now and have a detailed look at https://github.com/alibaba/nacos/blob/master/CONTRIBUTING.md. This document introduce how to commit code and create pull request.

**Comment by XCXCXCXCX** [comment]
@nkorange  Sorry, I only saw a short PR introduction before, now I will read and standardize it carefully.

**Comment by nkorange** [comment]
@XCXCXCXCX It's OK. We are glad you have the passion to contribute to Nacos. Do you have any IM account so I can contact you? Let's discuss this feature in detail and then put this feature forward together.

**Comment by JerryChin** [comment]
Need this implemented, it's a MUST-HAVE feature for every service registry.

**Comment by nkorange** [comment]
@JerryChin There are codes related to client-side load balancer: https://github.com/alibaba/nacos/blob/develop/client/src/main/java/com/alibaba/nacos/client/naming/core/Balancer.java

Maybe they could be extended to expose to user.
