### ISSUE TITLE
com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate#subscribe这个方法只支持com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate#grpcClientProxy

### ISSUE THREAD

**Issue by ddzcoeur** [alibaba/nacos#12539]
In the `com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate#registerService` method, the `httpClientProxy` is specified as the `com.alibaba.nacos.client.naming.NacosNamingService#clientProxy` through the `com.alibaba.nacos.api.naming.pojo.Instance#setEphemeral` configuration. However, in the `com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate#subscribe` method, it is not possible to use `httpClientProxy`, which leads to the ability to register services but not retrieve all instances using `getAllInstances`.

**Comment by ddzcoeur** [comment]
I believe that registerService and getAllInstances are paired methods, so it should be possible to specify the corresponding clientProxy for both.

**Comment by KomachiSion** [comment]
sorry, you might make a mistake about it.

httpClientProxy is an adapter for nacos1.x to nacos 2.x,  and it is deprecating and removing.

For the newest version, all of the client proxy feature has move to grpcClient but not http Client.

Why keep the httpClientProxy is that only little of feature should be adpater like register with persistent instance which support with grpc after 2.3.0.

About the `subscribe`, it has been adpater from 2.0.0 version, so it is no need to keep httpClientProxy version because 2.X client can't connect to 1.X server.
