### ISSUE TITLE
[Security Problem] CVE-2022-46337 by derby

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/nacos#12698]
**Describe the bug**

The package org.apache.derby with CVE-2022-46337

**Expected behavior**
Fix security issue

**Actually behavior**
No fixed version by offical release

**How to Reproduce**
Suggest replace to the 3rd party version: https://mvnrepository.com/artifact/org.apache.derby/derby/10.14.3.0-magnolia

**Comment by KomachiSion** [comment]
For Nacos community, it hard to upgrade to an 3rd party version which is not public on all repo.

And for office version, it need jdk19 at least, see https://github.com/alibaba/nacos/pull/11410

And for nacos situation, the issue not match I think, because the derby not use LADP feature and add some usage limit in Derby situation. So I think It's no risk to use.

If your local env need to upgrade version to pass the security scan, you can do this upgrade by yourself.
