### ISSUE TITLE
启动报错 2.4.1 

### ISSUE THREAD

**Issue by jsercom** [alibaba/nacos#12791]
Failed to instantiate [com.alibaba.nacos.naming.misc.SwitchManager]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: C:\Users\86138\AppData\Local\Temp\librocksdbjni2752963711702542417.dll: Can't find dependent libraries

使用 2.4.1 版本启动报错 单例模式

**Comment by jsercom** [comment]
系统缺少-Microsoft Visual C++ 2015 Redistributable

**Comment by crazyone2one** [comment]
1. window server服务器上安装了Microsoft Visual C++ 2015 Redistributable
2. 删除了data文件夹
3. 使用startup.cmd -m standalone 启动
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\librocksdbjni5463920614953729159.dll: Can't find dependent libraries
![image](https://github.com/user-attachments/assets/4b91c6b9-f7fb-4004-9a0a-c04c1af99ea3)

**Comment by KomachiSion** [comment]
duplicate with #4336
