### ISSUE TITLE
xxx.yaml file rollback, change type to text?

### ISSUE THREAD

**Issue by liuxiaokun** [alibaba/nacos#1575]
## I have a  xxx.yaml file, when I operate rollback, it works, but xxx.yaml file change type to text.
configuration rollback successfully, but it's type disappeared
Type: *bug report*

### Describe what you expected to happen

 It should be the  the original type (yaml)

### How to reproduce it (as minimally and precisely as possible)

1.  click history version.
2.  input data-id and group, and search.
3.  clikc rollback button, and it tips succeed, but the original file type became text.

### Tell us your environment

nacos version 1.0.1

**Comment by pigxcloud** [comment]
I had the same problem

nacos version: 1.1.0

os: macos 10.13

- config in db,  nacos version 1.0 up 1.1
![](http://pic.pigx.top/20190721184901_VFkXKM_Screenshot.jpeg)

- I try to run the console source code，yarn start  Normal

**Comment by daishenghao** [comment]
The configRollback page info is the response of path `HISTORY_CONTROLLER_PATH`.
And clicking the rollback button is equal to publish the selected configs.
When publishing the selected history record config, it sends post data to `CONFIG_CONTROLLER_PATH`.
So the problem is that there is no `type` in post data, then the `CONFIG_CONTROLLER_PATH` controller use the default type value. 
I think it is a bug.

**Comment by nkorange** [comment]
The type here is only for edit convenience and not stored in Nacos. So the result here is normal.
