### ISSUE TITLE
ControllerMethodsCache return incorrect method

### ISSUE THREAD

**Issue by jay2033** [alibaba/nacos#2591]
当访问NamespaceController里面的getNamespaces和getNamespace方法的时候ControllerMethodsCache返回的是checkNamespaceIdExist
原因：这三个api对应的restful api url是一样的

**Comment by wolfgangzhu** [comment]
Actually `ControllerMethodsCache` caches Http Method --> URI as key, and Method as Value. "The restful api url is same" is fine, because these urls fetch(operate on) the same resources.  for authorization purpose. 
if call `/v1/nacos/namespaces?show=all&namespaceId=xxx`, getNamespace(by namespace id)will be invoked. 
when calling `/v1/nacos/namespaces?checkNamespaceIdExist=true`, checkNamespaceIdExist will be invoked. 
and `/v1/nacos/namespaces getNamespaces` will be invoked.
