### ISSUE TITLE
dubbo.registry.address配置不生效一直报错 java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: failed to req API:localhost:8848/nacos/v1/ns/instance. code:500 msg: java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by juntianfuren** [alibaba/nacos#3468]
一直报错 java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: failed to req API:localhost:8848/nacos/v1/ns/instance. code:500 msg: java.net.ConnectException: Connection refused: connect

我把dubbo.registry.address注释或者配置成其他的参数，都还是显示这一个错误。

引入依赖的环境
spring.cloud                           Hoxton.SR1
pring.cloud.alibaba                2.2.0.RELEASE
spring.boot.                            2.2.4.RELEASE

## 配置信息
指定环境
#spring.profiles.active=uat
服务器端口。默认为 8080
server.port=8888
应用名称
spring.application.name=dubbo-01-provider
Nacos 作为注册中心的配置项##################
Nacos 服务器地址
spring.application.cloud.nacos.discovery.server-addr=47.106.185.x:8848
Dubbo 配置项，对应 DubboConfigurationProperties类 ############################
指定 Dubbo 服务实现类的扫描基准包
dubbo.scan.base-packages=com.jtfr.service
协议名称, 指明是 dubbo
dubbo.protocols.dubbo.name=dubbo
协议端口，-1 表示自增端口，从 20880 开始
dubbo.protocols.dubbo.port=20880
Dubbo 服务注册中心配置，对应 RegistryConfig 类
指定 Dubbo 服务注册中心的地址
dubbo.registry.address=spring-cloud://47.106.185.x:8848
Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
设置订阅的应用列表，默认为 * 订阅所有应用
dubbo.cloud.subscribed-services=*`

**Comment by KomachiSion** [comment]
Please change your issue title make other search friendly, and please edit your issue by using issue template to describe your problem.
Otherwise no one can help you.

**Comment by KomachiSion** [comment]
issue template:



**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.

**Comment by horizonzy** [comment]
make sure the nacos server is started.it looks like the port 8848 is not listen.

**Comment by goMatchHtc** [comment]
useless

**Comment by SeedZheng** [comment]
badly author explain

**Comment by sasuke39** [comment]
Changing your application server port  that make it work
