### ISSUE TITLE
一个2.5M的配置文件publishConfig时报错

### ISSUE THREAD

**Issue by 16boke** [alibaba/nacos#3496]
今天推送了一个2.5M的json配置文件到nacos，但是失败了，响应是：java.io.IOException: Error writing to server。
具体位置在是com.alibaba.nacos.client.config.http.ServerHttpAgent#httpPost方法中，被IO异常捕获了：
catch (IOException ioe) {
                LOGGER.error("[NACOS IOException httpPost] currentServerAddr: " + currentServerAddr, ioe);
                throw ioe;
            }
确认json文件格式没有问题

**Comment by KomachiSion** [comment]
请按照issue模版进行说明，否则缺少信息无法帮您。

**Comment by KomachiSion** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.

**Comment by MAGRY-GIT** [comment]
Tomcat 默认 post  提交2M  超过后会造成无法上传  修改方法如下：
找到 application.properties  添加 
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1
禁用改设置  或者根据自己情况进行设置
