### ISSUE TITLE
Deprecated Method Replace

### ISSUE THREAD

**Issue by linqunhui** [alibaba/nacos#3536]
**Is your feature request related to a problem? Please describe.**
See that there is a deprected method in JwtTokenUtils, which is still in use

**Describe the solution you'd like**
I replaced the deprected method

**Describe alternatives you've considered**
Jwts.parser().setSigningKey(secretKey)  replaced Jwts.parserBuilder().setSigningKey(secretKey)

**Additional context**
JwtTokenUtils
![15966967](https://user-images.githubusercontent.com/39516645/89500798-dd1ed980-d7f4-11ea-8812-32da052117e3.jpg)

**Comment by linqunhui** [comment]
JwtTokenUtils

**Comment by Maijh97** [comment]
Please use issue template to description your problem, thanks.

template like :

Describe the bug
A clear and concise description of what the bug is.

Expected behavior
A clear and concise description of what you expected to happen.

Acutally behavior
A clear and concise description of what you actually to happen.

How to Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Desktop (please complete the following information):

OS: [e.g. Centos]
Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
Module [e.g. naming/config]
SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
Additional context
Add any other context about the problem here.

**Comment by linqunhui** [comment]
OK  Modified

**Comment by KomachiSion** [comment]
@linqunhui Can you submit a PR to fix this issue?

**Comment by linqunhui** [comment]
> @linqunhui您可以提交PR来解决此问题吗？

可以

**Comment by linqunhui** [comment]
@KomachiSion   我刚才拉下来的代码里面 jjwts.jar是 io.jsonwebtoken:jjwt-api:0.10.5   这个弃用的修改是在io.jsonwebtoken:jjwt-api:0.11.2出现的     是否要更新pom 里面jjwt-api的版本

**Comment by linqunhui** [comment]
@KomachiSion  我刚才提交了代码 请查看

**Comment by KomachiSion** [comment]
@linqunhui two question:
1. I do not find your PR. Whether you just commit to your fork repo but not submit PR?
2. if we upgrade version to 0.11.2, will it be functionally affected? Or caused some dependency conflicts？

**Comment by linqunhui** [comment]
@KomachiSion   1.我不知道怎么提交PR      2.升级到0.11.2功能上没出现影响，没造成依赖冲突

**Comment by linqunhui** [comment]
@KomachiSion 刚提交RP 您看一下
