### ISSUE TITLE
nacos console web page logo is aliyun logo？ 

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#3560]
nacos web page logo change to nacos logo

**Comment by KomachiSion** [comment]
Please use issue template to description your issue, Thanks.

**Comment by KomachiSion** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.

**Comment by zzq1314zll** [comment]
我们现在nacos console 页面的logo 是阿里云的logo，我想把它替换成nacos 的logo

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/89777334-12516180-db3e-11ea-8e00-101fd0f9f50c.png)
I see the logo has been nacos'

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/89777390-2f863000-db3e-11ea-8a48-2f2f6f120e6d.png)
Do you want to replace this icon?
