### ISSUE TITLE
消费者提供服务,如果服务名称包含下划线,会出现bug

### ISSUE THREAD

**Issue by 15726698950** [alibaba/nacos#3578]
消费者提供服务,如果服务名称包含下划线,会出现bug,具体表现是在nacos 服务列表每次刷新列表,一会健康一会不健康

**Comment by KomachiSion** [comment]
Please use issue template to describe your problem, Thanks.

**Comment by KomachiSion** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.

**Comment by KomachiSion** [comment]
No response from author and issue is lacks necessary information. So close it
