### ISSUE TITLE
The nacos client did not encode in the post request

### ISSUE THREAD

**Issue by syapollo** [alibaba/nacos#3621]
Client such as: spring-cloud-starter-alibaba-nacos-discovery
The configured password is not encoded in the post, so the special symbol "+" is not supported.

**Comment by KomachiSion** [comment]
@syapollo I know your problem. It may be an enhancement for nacos-client.

Could you please use the issue template to modify the description of the issue so that others can understand the issue more easily?

**Comment by KomachiSion** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.

**Comment by syapollo** [comment]
Client such as: spring-cloud-starter-alibaba-nacos-discovery
The configured password is not encoded in the post, so the special symbol "+" is not supported.


Describe the bug
The nacos client did not encode in the post request

Expected behavior
After the client is configured with a user password, it can correctly connect to the nacos registration service.

Acutally behavior

After the client is configured with a user password, it cannot connect to the nacos registration service correctly, and an error is reported at startup because the authentication fails

How to Reproduce
Steps to reproduce the behavior:

1. Configure the nacos registration server on the client, including the user password for connecting to nacos, the password contains the "+" sign
2. Start the client
3. See error

Desktop (please complete the following information):

OS: [e.g. Centos]
Version [e.g. nacos-server 1.3.0, nacos-client 1.2.1]
Module [e.g. naming/config]
SDK [e.g. original, spring-cloud-starter-alibaba-nacos-discovery]

**Comment by horizonzy** [comment]
I have a try. password contains '+','@'.'%'.when login without encode password, it can operate normally. I think this pr #3668 cause #3992 . in server, not decode password when authenticate. client needn't encode the password
