### ISSUE TITLE
Windows 安装后不能成功启动startup.cmd

### ISSUE THREAD

**Issue by doteyzm** [alibaba/nacos#3705]
I can't start nacos successfully in windows system。When I use windows poweshell to start startup.cmd, it says “Unable to access jarfile D:\software\nacos\distribution\target\nacos-server.jar”。Can you help me how to solve this problem。Thanks！！！

**Comment by KomachiSion** [comment]
Please use issue template to describe your issue. Thanks.

**Comment by KomachiSion** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.

**Comment by KomachiSion** [comment]
No response and necessary information. Close issue
