### ISSUE TITLE
nacos server can't receive a delete request when client shutdown normally

### ISSUE THREAD

**Issue by robinZhao** [alibaba/nacos#3863]
**Describe the bug**
deregisterservice method in NamingProxy.class called successful when nacos-client shutdown，
but the service  shown in nacos-server  is still health for a while.
can't find delete request log in nacos's access_log

it's normal when using nacos-client1.2

use packages:
compile group: 'org.apache.dubbo', name: 'dubbo-spring-boot-starter', version: '2.7.7'
compile group: 'com.alibaba.boot', name: 'nacos-config-spring-boot-starter', version: '0.2.7'
compile group: 'com.alibaba.nacos', name: 'nacos-client', version: '1.3.1'

**Expected behavior**
the service shown in nacos is deleted

**Acutally behavior**
the service shown in nacos is normal

**How to Reproduce**
1. start dubbo service
2. shutdown dubbo service 
3. refresh nacos service dashboard

**Desktop (please complete the following information):**
 - OS: [windows 2010]
 - Version [nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [ naming ]
 - SDK [nacos-client]

**Additional context**

**Comment by KomachiSion** [comment]
As you said, server do not received the delete request. So there are two possible reason:
1. your client call is error. the request didn't send from client.
2. client send delete request, but the net has problem so that the request loss.

I test call deregisterservice directly, it works. So I think you need find the root reason your server do not received the delete request.

**Comment by robinZhao** [comment]
when closing process
nacos-client delete service  after  restclient destroyed
version 1.3.2 is normal
