### ISSUE TITLE
The bean 'nacosDiscoveryClient', defined in XXX has already been defined in class path resource  XXX

### ISSUE THREAD

**Issue by wangjia2016** [alibaba/nacos#3943]
**Describe the bug**
The bean 'nacosDiscoveryClient', defined in class path resource [com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientAutoConfiguration.class] and overriding is disabled.

**Expected behavior**
normal 

**Acutally behavior**

**How to Reproduce**
SpringBootWebApplication：
SpringBoot version 2.3.3.RELEASE
spring-cloud-dependencies Hoxton.SR8
spring-cloud-alibaba-dependencies 2.2.3.RELEASE

**Desktop (please complete the following information):**
 - OS: windows idea
 - Version  NACOS1.1.4

**Comment by horizonzy** [comment]
it seems that bean called nacosDiscoveryClient reRegisted, pls check `com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.class` did exist more than one. I think maybe you import two versions jar in your project

**Comment by KomachiSion** [comment]
spring hint both `NacosDiscoveryClientConfiguration.class` and `NacosDiscoveryClientAutoConfiguration.class` are bean 'nacosDiscoveryClient'.

It must import two version of `spring-cloud-alibaba`, because `NacosDiscoveryClientConfiguration` is old name of `NacosDiscoveryClientAutoConfiguration.class`
