### ISSUE TITLE
TCP/UDP service discovery support 

### ISSUE THREAD

**Issue by shyding** [alibaba/nacos#4058]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
Please description your feature in the comment with the template, only issue title no one can understand your feature.

**Comment by shyding** [comment]
Is your feature request related to a problem?
Yes



Describe the solution you'd like
One TCP or UCP server is discovered by Nacos;
Nacos can call TCP server or UDP server just like HTTP server


Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.
The client can call the TCP or UDP server through the service found by ncaos, just like calling the HTTP server

Additional context
Not yet

**Comment by KomachiSion** [comment]
I don't know what's your feature.

your service is TCP or UDP server is not different with HTTP server for nacos.
you just need to import nacos-client and register your actual address and port of TCP or UDP to nacos.

And your TCP or UDP subscriber app also import nacos-client to get the address and port so that your app can call the target service by yourself.

**Comment by KomachiSion** [comment]
No more response from author. Close issue.
