### ISSUE TITLE
The  config questions of nacos 

### ISSUE THREAD

**Issue by xu-weize** [alibaba/nacos#4138]
I want to ask some  questions: 
   (1) What is the difference between failoverFile and snapshotFile ,and when invoke checkLocalConfig method why use failoverFile?
   (2) Can you describe the case （cacheData.isUseLocalConfigInfo() && !path.exists() ）when invoke checkLocalConfig method
   (3) When fetch server config and  the respond result is success,why save snapshot and not failoverfile .What the case failoverfile can save?

**Comment by KomachiSion** [comment]
1. failoverFile is users defined, if there is failoverFile means users determine to use the config. So nacos-client will use failoverFile first. nacos-client only read failoverFile but not wrtie, so use failoverFile only when users create this file by themselves.

2. If you apps can't connect nacos but you want to change config right now, you can create failoverFile, and let nacos enter this condition to use your specified config.

3. snapshot is a local tmp storage which saved the configuration from server. FailoverFile is for failover situation only. They has different usages and priority. For example, you network has some problem so that your app can't connect nacos server, but you do not change the configuration, in this case, you restart your app, nacos can read snapshot config to set your parameters. But if your want to use new configuration, your snapshot is old version, you need use failoverFile to overwrite it so that your app can start correctly.

**Comment by xu-weize** [comment]
Thanks.From what you said，i can think so :  
     (1)The failoverfile is create by user , and  user to operates it only.
     (2) Nacos-client only read failoverFile but not wrtie,which means user app would to write it and may be different snapshot

**Comment by KomachiSion** [comment]
> Thanks.From what you said，i can think so :
> (1)The failoverfile is create by user , and user to operates it only.
> (2) Nacos-client only read failoverFile but not wrtie,which means user app would to write it and may be different snapshot

yes, it is.
