### ISSUE TITLE
com.alibaba.nacos.client.naming.net.HttpClient doesn't reused connection

### ISSUE THREAD

**Issue by maomaoke** [alibaba/nacos#4246]
**Why doesn't the com.alibaba.nacos.client.naming.net.HttpClient class use the connection pool to request a connection? This results in that after each heartbeat request, the tcp connection is actively closed, and the tcp connection cannot be reused.**

**Comment by KomachiSion** [comment]
We have used apache httpClient to replace the client's connection implementation in 1.3.1, but due to a large number of users feedback log printing problems. Finally, it was rollback in version 1.3.2. 

And in 2.x, we plan to use gRPC which is based on http2.0 and is long-timed connection mode to replace it.
So we just refactor it and implement with JDK http connection and apache http client for now.
