### ISSUE TITLE
NacosRule负载均衡获取的服务名错误

### ISSUE THREAD

**Issue by wangdejian163** [alibaba/nacos#4652]
spring cloud版本：Greenwich.SR2
nacos-discovery版本：2.1.3.RELEASE
nacos版本：1.3.2
1.有ServerA，ServerB两个服务，测试发现 。在启动类注入
`
 @Bean
    public IRule ribbonRule() {
        return new NacosRule();
    }
`
分别在浏览器访问ServerA，ServerB。
`
DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer)this.getLoadBalancer();
            String name = loadBalancer.getName();
`
发现name 除第一次正确外，后面再访问会一直是同一个服务。导致404错误。

**Comment by KomachiSion** [comment]
有收到服务的订阅信息吗？ 看一下${user.home}/logs/nacos/naming.log

**Comment by wangdejian163** [comment]
没有日志，nameing.log是空的。

**Comment by KomachiSion** [comment]
那过滤一下你的业务日志，可能是SCA覆盖了nacos的日志设置，打印到业务日志里了。

另外ribbon使用问题可能需要转到SCA社区，

**Comment by a13237009879** [comment]
问下 这个问题解决了么。目前我们也碰到了这个问题。

**Comment by ShingmoYeung** [comment]
我也碰到这个问题

**Comment by ShingmoYeung** [comment]
> 这个问题有解决么？？？

https://github.com/alibaba/spring-cloud-alibaba/issues/1652

**Comment by a13237009879** [comment]
解决了。注意springclientfactory的机制



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月12日(周四) 上午10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] NacosRule负载均衡获取的服务名错误 (#4652)




  
这个问题有解决么？？？
  
alibaba/spring-cloud-alibaba#1652
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aronlele** [comment]
是的，我查了下加载，就加了个Bean范围
