### ISSUE TITLE
使用源码构建

### ISSUE THREAD

**Issue by jinshengyong** [alibaba/nacos#4706]
在使用 mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U 进行源码构建的时候出现 
```
Compiling 2 proto file(s) to F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\target\generated-sources\protobuf\java
[ERROR] PROTOC FAILED: F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto: warning: directory does not exist.
F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\target\protoc-dependencies\8512915cc9d0310faa0434deb0e76df5: warning: directory does not exist.
F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\consistency.proto: No such file or directory

[ERROR] F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\consistency.proto [0:0]: F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto: warning: directory does not exist.
F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\target\protoc-dependencies\8512915cc9d0310faa0434deb0e76df5: warning: directory does not exist.
F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\consistency.proto: No such file or directory

[ERROR] F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\Data.proto [0:0]: F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto: warning: directory does not exist.
F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\target\protoc-dependencies\8512915cc9d0310faa0434deb0e76df5: warning: directory does not exist.
F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\consistency.proto: No such file or directory

```

的错误，有办法解决吗？

**Comment by wshzp12345** [comment]
可能是 目录名称有中文的问题 albert hou 邮箱：hzphlm@gmail.com 签名由 网易邮箱大师 定制 在2021年01月15日 10:11，jinshengyong 写道： 在使用 mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U 进行源码构建的时候出现 Compiling 2 proto file(s) to F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\target\generated-sources\protobuf\java

[ERROR] PROTOC FAILED: F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto: warning: directory does not exist.

F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\target\protoc-dependencies\8512915cc9d0310faa0434deb0e76df5: warning: directory does not exist.

F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\consistency.proto: No such file or directory



[ERROR] F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\consistency.proto [0:0]: F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto: warning: directory does not exist.

F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\target\protoc-dependencies\8512915cc9d0310faa0434deb0e76df5: warning: directory does not exist.

F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\consistency.proto: No such file or directory



[ERROR] F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\Data.proto [0:0]: F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto: warning: directory does not exist.

F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\target\protoc-dependencies\8512915cc9d0310faa0434deb0e76df5: warning: directory does not exist.

F:\工具\nacos-1.4.1\nacos-1.4.1\consistency\src\main\proto\consistency.proto: No such file or directory



 的错误，有办法解决吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jinshengyong** [comment]
确实是中文问题，谢谢哈
