### ISSUE TITLE
Nacos 持续输出PushReceiver日志

### ISSUE THREAD

**Issue by lsay-git** [alibaba/nacos#5524]
![image](https://user-images.githubusercontent.com/59008730/116368358-d4ff4200-a83a-11eb-9dc6-d581987139f8.png)

**Comment by brothelul** [comment]
Hi,@lsay-git .Is the Nacos version 2.0.0?

**Comment by wenyilu00007** [comment]
我们也遇到了，client是1.2.1的，nacos-server 2.0.0的

**Comment by brothelul** [comment]
好的，我这边复现一下，排查一下原因。

**Comment by brothelul** [comment]
It due to the information is printed out  in info level. you can change the naming level to warning or error temporary to solve this problem.
![image](https://user-images.githubusercontent.com/25661357/116402732-5a94e900-a85f-11eb-969a-8cd4fc528313.png)
I think this message can be printed in debug level to sovle the problem. Do you have any idea about this?

**Comment by KomachiSion** [comment]
duplicate with #5404
