### ISSUE TITLE
nacos dir configs for tomcat error

### ISSUE THREAD

**Issue by weissxu** [alibaba/nacos#5809]
**Describe the bug**

nacos dir configs for tomcat error！

**Expected behavior**
work and logs directory is located in the sub directory(eg. 7748)

**Acutally behavior**
work and logs directory is located in the nacos2.0 directory

**How to Reproduce**
When I deploy nacos with cluster mode in the same host with separate ports, 

1. the dirs is like below:
nacos2.0/
--7748
  --bin
  --other dirs
--8848
  --bin
  --other dirs
--9948
  --bin
  --other dirs

2. go to nacos2.0 directory

3. start the cluster
sh 7748/bin/startup.sh
sh 8848/bin/startup.sh
sh 9948/bin/startup.sh

4. then the tomcat related dir is appear here， and only one。
nacos2.0/
--7748
--8848
--9948
--work
--logs

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
in application.properties,config property as this:   

server.tomcat.basedir=${nacos.home}

then all is right!

**Comment by JackSun-Developer** [comment]
Do not use 7748 and 8848 and 9848 as the seperate ports to start nacos, because in nacos2.x, we use +1000 and -1000 method to calculate the grpc call port and raft election port.
![image](https://user-images.githubusercontent.com/58767027/119074616-f01c3680-ba21-11eb-89bf-1928e36da229.png)

The tomcat releted dir can be set by setting property 'server.tomcat.basedir'.

**Comment by KomachiSion** [comment]
Your problem is environment problem.

if you do not set `server.tomcat.basedir=` the default is your local dir.

For example, you startup nacos with 

```
sh 7748/bin/startup.sh
sh 8848/bin/startup.sh
sh 9948/bin/startup.sh
```

the server.tomcat.basedir= is dir `nacos2.0`. Then three nacos node will use same tomcat basedir and will conflict.

When you set `server.tomcat.basedir=${nacos.home}`. The three tomcat basedirs will change to `nacos2.0/7748`, `nacos2.0/8748` and `nacos2.0/9748`, which will not conflict. So it will be ok.
