### ISSUE TITLE
offline the instance meet error when use stand alone mode.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5911]
**Describe the bug**

click offline, meet error.
offline the instance meet error when use stand alone mode.

![image](https://user-images.githubusercontent.com/25661357/120216276-63674900-c269-11eb-8bf4-1d7559c09c44.png)

**Expected behavior**

offline currently

**Acutally behavior**

meet error.

**How to Reproduce**
1. Go to 'service detail'
2. Click on 'offline instance'
3. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-console 2.0.2 snapshot]
 - Module [e.g. nacos-console]

**Additional context**

no

**Comment by JackSun-Developer** [comment]
Remove the {nacos_home}/data/protocol and restart, then the problem will be solved. 
This is caused by the left jRaft cluster information.

**Comment by brotherlu-xcq** [comment]
I will try later.

**Comment by KomachiSion** [comment]
The reason is jraft will store the metadata of raft leader. But you local env ip maybe change after restart. So the last time leader ip and new env ip can't vote a new leader(not more than half). So all raft operation can't work well.

You can set the `-Dnacos.server.ip=127.0.0.1` or set `nacos.inetutils.ip-address=127.0.0.1` to avoid the problem.

When you has happen this problem, just like @JackSun-Developer said to fix it.
