### ISSUE TITLE
2.0.2 config data not exist

### ISSUE THREAD

**Issue by paopaoshimeng** [alibaba/nacos#6702]
**Describe the bug**
When i am using mysql database as my configcenter, i find my newly published configurations could not be find. I debug find that nacosClient get the response "config data not exist". However, when i use derby database, this bug is not exist.

**Expected behavior**
i want my newly published configuration can be find correctly.

**How to Reproduce**
1.use mysql as database to start nacos service -m standalone
2.publish the configuration which dataId org.apach.demo.service:1:1.condition-router

**Desktop (please complete the following information):**
 - OS: win10
 - Version 2.0.2
 - Module config
 - SDK nacos

**Additional context**

**Comment by MajorHe1** [comment]
排查一下跟mysql的数据库连接是否正常，当然，如果连接mysql不正常，nacos-server启动时会报错；
发布配置的时候没有异常和错误信息吗？

**Comment by brotherlu-xcq** [comment]
It's due to the `:` in your dataId, this will make the config dump failed in Nacos server(because the filleName will use the dataId). and the when you request this config, it will load the config from cache file not the mysql. the parse request config code is below. 

https://github.com/alibaba/nacos/blob/96706277243ab7d0d3c4ff0147b00c82cdc8f31b/config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java#L184-L188

additional, the special `:` also will cause the saveSnapshot failed in Nacos client.

I think if we want to support the special `:`, we need to replace this symbol to others like `@  ,    _`  when we use the it.

**Comment by paopaoshimeng** [comment]
> 排查一下跟mysql的数据库连接是否正常，当然，如果连接mysql不正常，nacos-server启动时会报错；
> 发布配置的时候没有异常和错误信息吗？

连接正常；发布配置的时候没有异常和错误；
发布的其他配置，如果没有两个“：”，比如org.apach.demo.service:11.condition-router，发布之后是可以查到的。
 而且所有的配置发布之后，在nacos的管理界面是能看到这些配置的信息的。

**Comment by paopaoshimeng** [comment]
> It's due to the `:` in your dataId, this will make the config dump failed in Nacos server(because the filleName will use the dataId). and then when you request this config, it will load the config from cache file not the mysql. the parse request config code is below.
> 
> https://github.com/alibaba/nacos/blob/96706277243ab7d0d3c4ff0147b00c82cdc8f31b/config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java#L184-L188
> 
> additional, the special `:` also will cause the saveSnapshot failed in Nacos client.
> 
> I think if we want to support the special `:`, we need to replace this symbol to others like `@ , _` when we use the it.

this is only happen when there are two ":" ,just one ":", the config can be found correctly.

**Comment by brotherlu-xcq** [comment]
yes, you are right.

**Comment by KomachiSion** [comment]
refer to #6700
