### ISSUE TITLE
nacos-server2.0.3 start fail in mac OS M1 pro 

### ISSUE THREAD

**Issue by xufan518** [alibaba/nacos#7024]
mac OS M1 pro nacos-server start error
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instanceOperatorClientImpl' defined in URL [jar:file:/opt/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.3.jar!/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/opt/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.3.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/opt/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.3.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/mc/f_dmjwd92cg1nyccjz8ks_3m0000gn/T/librocksdbjni4019066135788166614.jnilib: dlopen(/private/var/folders/mc/f_dmjwd92cg1nyccjz8ks_3m0000gn/T/librocksdbjni4019066135788166614.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/mc/f_dmjwd92cg1nyccjz8ks_3m0000gn/T/librocksdbjni4019066135788166614.jnilib: mach-o, but wrong architecture
	/private/var/folders/mc/f_dmjwd92cg1nyccjz8ks_3m0000gn/T/librocksdbjni4019066135788166614.jnilib: mach-o, but wrong architecture
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)

**Comment by haohai2212** [comment]
plus

**Comment by haohai2212** [comment]
同问，你解决了没

**Comment by Mother-Ship** [comment]
同问，目前切1.4.2使用

**Comment by zmlgit** [comment]
貌似是底层io库的问题，我Google了一下，大多数都是说grpc 的错误

` com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: ErrCode:500, ErrMsg:Function not implemented
nacos-standalone-mysql | 	at com.alibaba.nacos.core.listener.StartingApplicationListener.loadPreProperties(StartingApplicationListener.java:161)
nacos-standalone-mysql | 	at com.alibaba.nacos.core.listener.StartingApplicationListener.environmentPrepared(StartingApplicationListener.java:100)
nacos-standalone-mysql | 	at com.alibaba.nacos.core.code.SpringApplicationRunListener.environmentPrepared(SpringApplicationRunListener.java:65)
nacos-standalone-mysql | 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
nacos-standalone-mysql | 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
nacos-standalone-mysql | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
nacos-standalone-mysql | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
nacos-standalone-mysql | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
nacos-standalone-mysql | 	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
nacos-standalone-mysql | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos-standalone-mysql | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos-standalone-mysql | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos-standalone-mysql | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos-standalone-mysql | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
nacos-standalone-mysql | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
nacos-standalone-mysql | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
nacos-standalone-mysql | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
nacos-standalone-mysql | Caused by: com.alibaba.nacos.api.exception.NacosException: java.io.IOException: Function not implemented
nacos-standalone-mysql | 	at com.alibaba.nacos.sys.file.WatchFileCenter$WatchDirJob.<init>(WatchFileCenter.java:189)
nacos-standalone-mysql | 	at com.alibaba.nacos.sys.file.WatchFileCenter.registerWatcher(WatchFileCenter.java:97)
nacos-standalone-mysql | 	at com.alibaba.nacos.core.listener.StartingApplicationListener.registerWatcher(StartingApplicationListener.java:167)
nacos-standalone-mysql | 	at com.alibaba.nacos.core.listener.StartingApplicationListener.loadPreProperties(StartingApplicationListener.java:159)
nacos-standalone-mysql | 	... 16 common frames omitted
nacos-standalone-mysql | Caused by: java.io.IOException: Function not implemented
nacos-standalone-mysql | 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
nacos-standalone-mysql | 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
nacos-standalone-mysql | 	at com.alibaba.nacos.sys.file.WatchFileCenter$WatchDirJob.<init>(WatchFileCenter.java:184)
nacos-standalone-mysql | 	... 19 common frames omitted`

**Comment by KomachiSion** [comment]
duplicate with #4336
