### ISSUE TITLE
Failed to bind properties under 'server.tomcat.basedir' to java.io.File

### ISSUE THREAD

**Issue by lironghai** [alibaba/nacos#7063]
修改代码后使用nacos-docker项目提供dockerfile 制作镜像， 启动容器报错   Failed to bind properties under 'server.tomcat.basedir' to java.io.File   

Description:

Failed to bind properties under 'server.tomcat.basedir' to java.io.File:

    Property: server.tomcat.basedir
    Value: 
    Origin: InputStream resource [resource loaded through InputStream] - 105:0
    Reason: failed to convert java.lang.String to java.io.File (caused by java.lang.IllegalStateException: Could not retrieve file for class path resource []: class path resource [] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/)

是否需要修改配置文件

**Comment by bluce-clj** [comment]
158 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug'      enabled.
 159                                                                                  
 160 2022-06-06 17:53:03,622 ERROR·                                                   
 161                                                                                  
 162 ***************************                                                      
 163 APPLICATION FAILED TO START                                                      
 164 ***************************                                                      
 165                                                                                  
 166 Description:                                                                     
 167                                                                                  
 168 Failed to bind properties under 'server.tomcat.basedir' to java.io.File:         
 169                                                                                  
 170     Property: server.tomcat.basedir                                              
 171     Value:·                                                                      
 172     Origin: class path resource [application.properties] from nacos-server.jar - 105:0
 173     Reason: failed to convert java.lang.String to java.io.File (caused by java.lang.IllegalStateExceptio     n: Could not retrieve file for class path resource []: class path resource [] cannot be resolved to abso     lute file path because it does not reside in the file system: jar:file

**Comment by KomachiSion** [comment]
Refer to #8960
