### ISSUE TITLE
Why is it defined but not used？

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#7538]
Why is it defined but not used？ I look terrible.
As shown in the figure:
![image](https://user-images.githubusercontent.com/33930711/147856313-85a17c4e-aaee-40a9-92d8-940cfe15d54b.png)

**Comment by onewe** [comment]
I'm sorry about that, It's part of my pr. I'm going to optimize some about constant problems(you can see here:https://github.com/alibaba/nacos/issues/5726), but I had found that this is a large project and splited pr(here:https://github.com/alibaba/nacos/issues/7225) to five parts, because some reasons is only merge a part of pr. That is why it has been there.

@zzq1314zll
