### ISSUE TITLE
can Distro verify task send verifyData to other member use batch request?

### ISSUE THREAD

**Issue by bjxiaojian** [alibaba/nacos#8123]
DistroClientDataProcessor.java
```
    @Override
    public List<DistroData> getVerifyData() {
        List<DistroData> result = new LinkedList<>();
        for (String each : clientManager.allClientId()) {
            Client client = clientManager.getClient(each);
            if (null == client || !client.isEphemeral()) {
                continue;
            }
            if (clientManager.isResponsibleClient(client)) {
                // TODO add revision for client.
                DistroClientVerifyInfo verifyData = new DistroClientVerifyInfo(client.getClientId(), 0);
                DistroKey distroKey = new DistroKey(client.getClientId(), TYPE);
                DistroData data = new DistroData(distroKey,
                        ApplicationUtils.getBean(Serializer.class).serialize(verifyData));
                data.setType(DataOperation.VERIFY);
                result.add(data);
            }
        }
        return result;
    }
```

DistroVerifyExecuteTask.java
```
    @Override
    public void run() {
        for (DistroData each : verifyData) {
            try {
                if (transportAgent.supportCallbackTransport()) {
                    doSyncVerifyDataWithCallback(each);
                } else {
                    doSyncVerifyData(each);
                }
            } catch (Exception e) {
                Loggers.DISTRO
                        .error("[DISTRO-FAILED] verify data for type {} to {} failed.", resourceType, targetServer, e);
            }
        }
    }

```

1. in distro v2，a verifyData means a clientId and version，if there are thousands of client connect on a server，this will send thousands of request to target member?
2. think about package all clientId（if worry aobut data too large, can config batchSize）into a DistroData content，so it can send a request to target member instead of  send thousands of request .

**Comment by KomachiSion** [comment]
verify need fast and simple to update and check data. So each verify data need small and check logic should handle quick.
and when check failed, we should sync new data to target server immediately. So I think one client one verify is better and alibaba has run in this mode for a long time. 

There may be an enhancement is shuffer client. Now the verify task will send all client verify, and after an internal time send all clients again, we can think a way to  balance these client verify tasks to make task run in all internal time. It also some problem need to solve, such as clients is changing.

**Comment by bjxiaojian** [comment]
1. I don't think package all client into a request will make the verify data slow then one client a request, for example there are 1000 client need to send verify to other member, maybe the first client verify data will slower then now, but most of the other client will be faster then now. And I don't think the logic will be mush more complicated.
2. As you saying alibaba has run in this mode for a long time, I think the way now using not be a serious performance problem, but can be improve verify speed in package client way.

**Comment by KomachiSion** [comment]
If you think package all client can solve your performance problem , you can modify in your fork repo. But in our practice, send much client in a big package will cause many time and max size problem. So we use simple package and `faster` way to verify one client each time.

problem list we has found:
1. many clients for one verify will cause the package is so large that match the max size of grpc request, if only set max size of grpc will lead to memory vulnerability and poor network resistance.
2. many clients for one verify mean receiving  server will handle many client in one request, and will return all client which not  verify passed. It cost much time and easy to block by thread switch or GC.
3. If we split all clients to many package, we will solve the consistence problem, because the clients is always changes, and your split package may has expired.

after using single client single verify, the first problem disappear. each verify only check one client and only return true or false, which is simple and faster. thread switch has less effect for verify and GC can release more memory which has finish verified.
For third problem, if one client expire just ignore it. Don't need to judge which clients in package has expired.

The way will cause there are many verify requests between servers, but it is not a big problem for grpc and long connection after performance test. So it is the choice. Of course, there are also some enhancement todo, such as average the verify request to whole interval.

**Comment by bjxiaojian** [comment]
I get your point of view, i close the issue. Maybe next time i can commit a pr to deal with shuffer. Thanks.
