### ISSUE TITLE
Normalize the release cycle based on semantic versioning

### ISSUE THREAD

**Issue by qngl** [alibaba/nacos#9008]
**Is your feature request related to a problem? Please describe.**
Make more releases and more frequently and follow the semantic versioning practice. 

**Describe the solution you'd like**
Follow the semantic versioning standard to plan the release. We can create a bug fix release very soon and safely, for example, 2.1.2 can only have some bug fixes based on version 2.1.1, and be released within a short release cycle, maybe 1 week. If there is some new features included, then the version number should be 2.2.0, which can have a longer release cycle. 
Please refer the [Semantic Versioning](https://semver.org/).

**Describe alternatives you've considered**
If we do the releases without a good(healthy) plan, we will loose users. As no version is stable enough to be used in production.

**Additional context**
There 4 months between v2.1.0 and v2.1.1, and quite a few bug fixes and new features. It means no stable version could be found in any 2.x.x versions. Then how do you want user to choose a 2.x.x version? More and more new features are nice, but stable is also important.

**Comment by KomachiSion** [comment]
I don't think nacos not follow `semantic versioning practice`.

in 2.0.x, the only the first 2.0.0 is completely new features, 2.0.1~2.0.4 just do fixes and enhancements. Some of new feature is only usage feature, which means the default UI changes, no effect the core features.

in 2.1.x, the only the first 2.1.0 is completely new features for plugin, 2.1.1's feature is beta feature which mean no need to use them if you don't need. The other changes most is fixes and enhancements.

About the stable version, you should judge it by yourself. The all of formal released version is stable enough. Of course there are some bugs in each versions, no body can confirm one version has no bugs. The key point is whether these feature bugs you used or dependency.

About the short release cycle, I think it depend what steps of this version and community contribute. We has a frequently release between 1.3.X ~ 2.0.3. The released interval about one month. One reason is 1.3 version has much more refactor and prefer for 2.X. Seconds is the 2.0.X is new structure so that more enhancement. At this time, community response the released is too frequently, don't know which version is stable. They just finished researching and preparing a version for deployment, and a new version is released. So nacos community start to refer to the release rhythm of other more open source communities, such as the apache community -- two to three month one released.

**Comment by KomachiSion** [comment]
No more discussion from community, I think this is a stoppable discussion.
