### ISSUE TITLE
windows can not save nacos config snapshot

### ISSUE THREAD

**Issue by 17701057157** [alibaba/nacos#943]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
when i debug nacos client on windows, i found nacos config can not generate snapshot on local disk, becuase windows does not accept ":" in directory.  
   the directory on my windows is "C:\Users\liuql\nacos\config\fixed-localhost:8848_nacos\snapshot\DEFAULT_GROUP\springboot2-nacos-config"
   
### How to reproduce it (as minimally and precisely as possible)

1. when is copy the demo code from nacos server NACOS1.0.0-RC1 UI -> "详情|[示例代码]|编辑|删除|更多", the "示例代码" button
2. debug in idea 
3. see the picture file in attach files.
![微信图片_20190321164104](https://user-images.githubusercontent.com/10647594/54741059-279bb800-4bf8-11e9-9122-28682cb462b5.jpg)

### Tell us your environment
os: windows 10
maven: 
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.1</version>
        </dependency>
demo code is from the demo code is from nacos server NACOS1.0.0-RC1 UI -> "详情|[示例代码]|编辑|删除|更多", the "示例代码" button.

**Comment by 17701057157** [comment]
补充一个调试图：

![image](https://user-images.githubusercontent.com/10647594/54742036-32a41780-4bfb-11e9-9e90-b4351bfe3785.png)

**Comment by xuechaos** [comment]
@17701057157 what means  "windows does not accept ':' in directory". it work on win7? , could you show the error log detail? thank you.

**Comment by Razor0719** [comment]
This problem is still happening on Windows10 with nacos V1.1.0
The following is the error log:

01 2019-07-12 14:58:42.331 ERROR [com.alibaba.nacos.client.Worker.longPullingfixed-localhost:8848:c.a.n.c.c.i.LocalConfigInfoProcessor] [fixed-localhost:8848] [] [NACOS-XXXX] save snapshot error, *******\nacos\config\fixed-localhost:8848_nacos\snapshot\DEFAULT_GROUP\upns, java.io.FileNotFoundException: C:\Users\byl5026\nacos\config\fixed-localhost:8848_nacos\snapshot\DEFAULT_GROUP\test(文件名、目录名或卷标语法不正确。)

we can only make directory without ":" on Windows 10

**Comment by nkorange** [comment]
@Razor0719 Is your client version the latest?

**Comment by Razor0719** [comment]
> @Razor0719 Is your client version the latest?

yeah, the following is the dependency config:
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>0.1.1</version>
</dependency>
and the spring boot version is 1.5.4.RELEASE
